import "./style.scss";
// import {} from "./blocks/Banner";
// import {} from "./blocks/Services";
// import {} from "./blocks/Feature";
// import {} from "./blocks/Outsource";
// import {} from "./blocks/About";
// import {} from "./blocks/Clients";
// import {} from "./blocks/Feedback";
// import {} from "./blocks/Teams";
// import {} from "./blocks/CaseStudy";
// import {} from "./blocks/AboutBanner";
// import {} from "./blocks/Overview";
// import {} from "./blocks/Guarantee";
// import {} from "./blocks/Certificate";
// import {} from "./blocks/FunctionList";
// import {} from "./blocks/Product/VISInsight/Banner";
// import {} from "./blocks/Product/VISInsight/Overview";
// import {} from "./blocks/Product/Veramine/Banner";
// import {} from "./blocks/Product/Veramine/Technology";
// import {} from "./blocks/Product/Veramine/Overview";
// import {} from "./blocks/BlogFeatured";
// import {} from "./blocks/BlogTags";
// import {} from "./blocks/BannerCommon";
// import {} from "./blocks/DevelopingMobile";
// import {} from "./blocks/DevelopmentOurProcess";
// import {} from "./blocks/DevelopmentBenefit";
// import {} from "./blocks/ServiceHead";
// import {} from "./blocks/BlockChain";
// import {} from "./blocks/BannerNew";
// import {} from "./blocks/Leadership";
// import {} from "./blocks/ServiceNew";
// import {} from "./blocks/BannerNewImg";
// import {} from "./blocks/BannerServicePage";
// import {} from "./blocks/TheFox";
// import {} from "./blocks/Process";
// import {} from "./blocks/FeatureServicePage";

import {} from "./blocks/ServiceNew";
import {} from "./blocks/BannerNewImg";
